version: "3.9"
services:

  application:
    hostname: ${APPLICATION}
    container_name: ${APPLICATION}
    build: .
    restart: always
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    environment:
      JAVA_OPTS: |
        -Dspring.profiles.active=docker
        -Dserver.port=${APPLICATION_PORT}

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}